// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzIxNBpRzsTUdo8tDcub7TdpZGTePUgbU',
    appId: '1:182680255149:web:b1faab8e674aa2da502424',
    messagingSenderId: '182680255149',
    projectId: 'iot-sec-948c9',
    authDomain: 'iot-sec-948c9.firebaseapp.com',
    databaseURL: 'https://iot-sec-948c9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-sec-948c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22LWbbAGrmju-xOGYnD7Ky7VxL5OIHPQ',
    appId: '1:182680255149:android:7557610d609109a2502424',
    messagingSenderId: '182680255149',
    projectId: 'iot-sec-948c9',
    databaseURL: 'https://iot-sec-948c9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-sec-948c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLIEQ79TDq69EYH9ajhcDHDw6-PNNge4',
    appId: '1:182680255149:ios:d8fc3044a8633e2a502424',
    messagingSenderId: '182680255149',
    projectId: 'iot-sec-948c9',
    databaseURL: 'https://iot-sec-948c9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-sec-948c9.appspot.com',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLIEQ79TDq69EYH9ajhcDHDw6-PNNge4',
    appId: '1:182680255149:ios:d8fc3044a8633e2a502424',
    messagingSenderId: '182680255149',
    projectId: 'iot-sec-948c9',
    databaseURL: 'https://iot-sec-948c9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-sec-948c9.appspot.com',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzIxNBpRzsTUdo8tDcub7TdpZGTePUgbU',
    appId: '1:182680255149:web:1d1317e6fda9e6b1502424',
    messagingSenderId: '182680255149',
    projectId: 'iot-sec-948c9',
    authDomain: 'iot-sec-948c9.firebaseapp.com',
    databaseURL: 'https://iot-sec-948c9-default-rtdb.firebaseio.com',
    storageBucket: 'iot-sec-948c9.appspot.com',
  );
}
